### ISSUE TITLE
Connection problem when using eth -i

### ISSUE THREAD

**Issue by jesuscript** [ethereum/node-ethereum#11]
Not sure if this is a node issue or cpp but thought I'd log it anyway:

cpp client: 

```
> connect 0.0.0.0 30303
+N+ [ 13:17:58 | main ] Attempting connection to 0.0.0.0:30303
+N+ [ 13:17:58 | p2p ] Connected to 0.0.0.0:30303
-N- [ 13:17:58 | p2p | 19 ] Disconnect (reason: Data format error. )
*N* [ 13:17:58 | p2p | 19 ] Closing 127.0.0.1:30303
```

node:

```
info connection 
info networking 127.0.0.1:61540 closing
```

**Comment by MattBeton** [comment]
I am having this same problem. I am mining with my GTX 970, But I just get an error message saying couldn't interpret package every 3 seconds. Here is my log (I have removed all long Numbers/codes for privacy reasonds, and because they would get in the way. They have been replaced with [CODE]):

```
`C:\Program Files\Ethereum 0.9.41\Release>eth -G
(++)Ethereum
Beware. You're entering the Frontier!
Found suitable OpenCL device [GeForce GTX 970] with 4294967296 bytes of GPU memory
  i  18:27:53|main  Reading C:\Users\matth\AppData\Roaming\Web3/keys\6749d005-b910-19b0-899b-3e03e69d68f3.json
  i  18:27:54|main  Opened blockchain DB. Latest: #511b9a33ÔÇª (rebuild not needed)
  i  18:27:54|main  Opened state DB.

Please enter your MASTER password: Ethereum (++) 0.9.41
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
Transaction Signer: [CODE] ([CODE] - [CODE])
Mining Beneficiary: [CODE] ([CODE] - [CODE])
Foundation: [CODE] (00000000-0000-0000-0000-000000000000 - [CODE])
  i  18:28:13|p2p  UPnP device: http://192.168.1.1:41041/rootDesc.xml [st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 ]
Node ID: enode://[CODE]@[IP]:[PORT]
N X  18:28:13|p2p|a979fb57ÔÇª|Geth/v1.3.3-c541b38f/linux/go1.5.1  Couldn't interpret packet. [ 0x3D, 0x1, [CODE], [CODE], [CODE] ]`
```

**Comment by wanderer** [comment]
@MattyAB This is deperacated.  Please check out [node-blockchain-server](https://github.com/ethereumjs/node-blockchain-server) it downloads and indexes the blockchain. You then can run the VM over the indexed chain.

**Comment by MattBeton** [comment]
@wanderer How am able to run this? It is just a bunch of .js files...

Help would be appreciated! 

Thanks!

**Comment by wanderer** [comment]
@MattyAB clone it then do npm install. Then run node ./index.js and it will connect to a client running locally. You can control what it connects to [here](https://github.com/ethereumjs/node-blockchain-server/blob/master/index.js#L122-L126)
