### ISSUE TITLE
Load Saved Peers

### ISSUE THREAD

**Issue by wanderer** [ethereum/node-ethereum#26]
related to #3. Need to saved load peers from the DB

**Comment by Latrasis** [comment]
I'm assuming this is in networking.js, and loading them meaning connecting to them?

**Comment by wanderer** [comment]
We need to load the saved peers on startup. That should go in somewhere in the [startup sequence](https://github.com/ethereum/node-ethereum/blob/master/lib/index.js#L51) . Then the loaded peers should be given to the network. It probably should be attached to the results object. And it wouldn't be bad if we renamed results to options [here](https://github.com/ethereum/node-ethereum/blob/master/lib/networking.js#L6). after network.js has the peers iterate through them and [connect](https://github.com/ethereum/ethereumjs-lib/blob/master/docs/networking.md#networkconnectport-host-callback).

**Comment by Latrasis** [comment]
Quick question: does [.getPeerList()](https://github.com/ethereum/ethereumjs-lib/blob/master/docs/networking.md#networkgetpeerlist) include all previous session existing peers as well or are they only based on the current session?

**Comment by wanderer** [comment]
only the current session.

**Comment by wanderer** [comment]
only the current session.

**Comment by Latrasis** [comment]
A bit confused, not sure where to start connecting the peers to, at where does network.js start connecting to peers? Or is this to be put in tasks?

**Comment by wanderer** [comment]
I would just put a for loop [here](https://github.com/ethereum/node-ethereum/blob/master/lib/networking.js#L18). You don't need to use the callback in [connect](https://github.com/ethereum/ethereumjs-lib/blob/master/docs/networking.md#networkconnectport-host-callback).

**Comment by wanderer** [comment]
done in  cc28da6
