### ISSUE TITLE
peer managemnt

### ISSUE THREAD

**Issue by wanderer** [ethereum/node-ethereum#32]
better peer management. Right now we just try to reconnect to all the prevous know peers.

**Comment by Latrasis** [comment]
Can you elaborate?

**Comment by wanderer** [comment]
sure. we need a scoring mechanism.  I think the first set would be to store a score along with each peer. Then each time client tries to reconnect to a peer and fails deincrement its score if succeeds increment its score. Later we will have to delete peers that fail beneath a certain threshold score.

**Comment by Latrasis** [comment]
How does starting Rep with 3 sound?

**Comment by wanderer** [comment]
maybe just 0?
