### ISSUE TITLE
dbServer does not close when client exits

### ISSUE THREAD

**Issue by kumavis** [ethereum/node-ethereum#36]
when you run node-ethereum again, you get an error b/c the old instance is still running.

you should be able to make the dbServer a child process so it closes by default... right?

**Comment by wanderer** [comment]
yes defaintly! that was working. should be happening here https://github.com/ethereum/node-ethereum/blob/develop/lib/index.js#L293

**Comment by kumavis** [comment]
@wanderer  are we sure that stop is being called on keyboard interupt?

**Comment by wanderer** [comment]
stop is being called here https://github.com/ethereum/node-ethereum/blob/develop/bin/ethereum#L25-L26

**Comment by kumavis** [comment]
maybe a different issue... closing for now
