### ISSUE TITLE
RPC methods for Vapor support

### ISSUE THREAD

**Issue by kumavis** [ethereum/node-ethereum#44]
We need these in the near term for vapor support
- [x] `eth_call`
- [x] `eth_changed`
- [x] `eth_newFilter`
- [x] `eth_signed_trans`*

`eth_signed_trans` is a nonstandard rpc method.

**Comment by kumavis** [comment]
`eth_changed`

polling method, which returns array of logs which occurred since last poll

request:
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_changed","params":[0],"id":73}' http://localhost:8080
response:
{
"id":1,
"jsonrpc":"2.0",
"result": [{
  "address":"0x0000000000000000000000000000000000000000",
  "data":"0x0000000000000000000000000000000000000000000000000000000000000000",
  "number":"0x1b4" // 436
  }]
}

**Comment by kumavis** [comment]
`eth_newFilter`

creates watch object to notify, when state changes in particular way, defined by filter. Returns new filter id.

request:
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topic":"0x12341234"}],"id":73}' http://localhost:8080`
response:
```
```

**Comment by wanderer** [comment]
just added `eth_signed_tx`. Right now it returns _everything_ so like this
``
  { gasUsed: {},
     fromAccount: 
      { nonce: '01',
        balance: 'ffec77',
        stateRoot: '56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
        codeHash: 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470' },
     toAccount: 
      { nonce: '',
        balance: '',
        stateRoot: '56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
        codeHash: '58034ccd203240454a56b9cfed59d67385f35af815702f624f7f454b21126262' },
     createdAddress: { type: 'Buffer', data: [Object] },
     vm: 
      { suicide: false,
        suicides: [],
        gasRefund: {},
        account: [Object],
        exception: 1,
        logs: [],
        returnValue: [Object],
        gasUsed: {} },
     bloom: { bitvector: [Object] },
     callerAccount: 
      { nonce: '01',
        balance: 'fffc18',
        stateRoot: '56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
        codeHash: 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470' },
     amountSpent: {} } }
```

**Comment by kumavis** [comment]
thanks @wanderer you are amazing
