### ISSUE TITLE
source repository & error

### ISSUE THREAD

**Issue by klkim** [ethereum/node-ethereum#45]
When I clone from http://github.com/wanderer/node-ethereum  guided in README.md, I met an error 

*info app problem with settings.json: Error: Cannot find module '/Users/xxx/.ethereum-node/settings.json'
Assertion failed: (obj->HasIndexedPropertiesInExternalArrayData()), function Data, file ../src/node_buffer.cc, line 103.
Abort trap: 6*

after typing $ ./bin/ethereum. In this case, **settings.json** in bin folder says, {"logging":3}.

However, cloning from https://github.com/ethereum/node-ethereum, I met an error too

*Assertion failed: (obj->HasIndexedPropertiesInExternalArrayData()), function Data, file ../src/node_buffer.cc, line 103.
Abort trap: 6*

In this case **settings.json** in bin folder says, 

{
  "logging": 3,
  "plugins": [
    "../plugins/ws/ws.js",
    "../plugins/webUI/"
  ],
  "network": {
    "port": 30303,
    "host": "0.0.0.0"
  },
  "upnp": true
}

I am using node v0.12.0, npm 2.5.1 on mac osx 10.10.2.

**Comment by wanderer** [comment]
are you on the dev branch?

**Comment by kumavis** [comment]
the readme does not specify dev
I would just move all the work to master, since there isnt really a notion of stability yet
one all required functionality is in place, the two branch system makes sense

**Comment by kumavis** [comment]
@klkim sorry for the confusion!

**Comment by wanderer** [comment]
updated the readme a bit. Maybe we should put a `unstable use at own risk` type of thing on in the readme? wdyt?

**Comment by kumavis** [comment]
@klkim closing for now, let us know if you have any other problems
