### ISSUE TITLE
xhrrpc does not return error

### ISSUE THREAD

**Issue by kumavis** [ethereum/node-ethereum#49]
it should, but we get back {} somehow....

```js
rpc.processRpc(message, function(err, data){
        if (err) {
          res.status(500).send({ error: err.message });
        } else {
          res.send(data);
        }
      });
```

**Comment by kumavis** [comment]
maybe setting the status returns before we send the {errror: err.message}?

**Comment by kumavis** [comment]
ah, you're returning a string for the error instead of an error object

**Comment by jorisbontje** [comment]
JSONRPC error handling is defined in http://www.jsonrpc.org/specification#error_object

**Comment by kumavis** [comment]
I patched this, so im closing
